### ISSUE TITLE
ToDo: Check offset

### ISSUE THREAD

**Issue by Splamy** [ReSpeak/quicklz#1]
Check here:
https://github.com/ReSpeak/quicklz/blob/35f6e71a0473f3be4a9c515d83fecfe7d6c7c42d/src/lib.rs#L189-L204
if `offset + matchlen < dec_size` and maybe also `offset < vec.len()`

**Comment by Flakebi** [comment]
I think if `offset >= vec.len()`, it should fail here in `copy_buffer_bytes`:
https://github.com/ReSpeak/quicklz/blob/35f6e71a0473f3be4a9c515d83fecfe7d6c7c42d/src/lib.rs#L66-L68

This should also catch `offset + matchlen > dec_size` as `res.len() + matchlen > dec_size` is checked and `offset >= vec.len()` too (the part above).
