### ISSUE TITLE
hashtable scope problem

### ISSUE THREAD

**Issue by rogue-shadowdancer** [ReSpeak/quicklz#6]
Recently I use rust to refactoring  a decompress tool, and I found there might be a problem of hashtable.
In C version, the function `qlz_decompress()` will transmit a parameter called `state_decompress`, which contains the array of hashtable. That means the hashtable might be used in different compressed packages(the pointer of offset might point to decompressed datas to get value if matchlen != 0).
But in your rust implementation of quicklz, hashtable is defined only when program enter the function `quicklz::decompress()`. So, in the decompress progress of second and later compressed packages, the problem is more likely to cause a error, because the hashtable is empty while matchlen is not zero.
I do not know if I said clearly, and I am very happy to contact with you for more details.

**Comment by Flakebi** [comment]
(Sorry for the late response)

Right, the state is not exposed, so `decompress()` can only be called on data that is completely available.
That’s enough for my use-case, but if you want to extend a state struct in the API, I’m happy to accept contributions :)
